# GitHub Actions workflow for deploying a Node.js application to Azure Web App
name: Build and deploy Node.js app to Azure Web App - nittvoice-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Change working directory to server for npm commands
      - name: npm install, build, and test
        working-directory: ./server
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      # Create zip from server directory
      - name: Zip artifact for deployment
        run: |
          cd server
          zip -r ../release.zip ./*

      # Upload the zip file as an artifact
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: |
          mkdir server
          unzip release.zip -d server
          rm release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_68C9D95BC76A4B8FA1A8224BD13AB382 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8952431FD576412C8043E74DCD85C33B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B4D6DA5F09E948B2B145E557D39E9078 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'nittvoice-backend'
          slot-name: 'Production'
          package: ./server